angular.module('imageApp', []).controller('ImageCtrl', function MainCtrl() {
  this.image = {
    background: 'data:image/jpeg;base64,/9j/4AAQSkZJRgABAQEAAQABAAD/2wBDAAEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQH/2wBDAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQH/wAARCAAKAA0DASIAAhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAACQr/xAAeEAACAgMBAQEBAAAAAAAAAAACAwQFAQYHCAkTEf/EABQBAQAAAAAAAAAAAAAAAAAAAAX/xAAhEQEAAgIBAwUAAAAAAAAAAAABAhEDIQQSMXEAExRCUv/aAAwDAQACEQMRAD8ASb1L3TPnX2B635loPbx0Ks6rukqfuGiWEq+tFFtO+6ZRHjc9bjUNzFpyoYEi7sz6XQoKD0VmZMHFa781R8RHy+dtBSav5C5Tr+ttGTR1atkRAnYHCMT/ANNmtpE2WEQmubBUVi6YtEGQ1smLHUpUhrW4JpxHfSCJEP6WehHHFjm2R1Tapj2klZMfLizgixZTjyOSZJjRlKjoeeSalClpWQrARxZX8plrV5KpkKAFoRtt2KUrEQUkWVevvYKljjALE3ua48BjGCa1jC/pmWcl8aR8zLEO0ctbWj3ILR227fGvSvIivChK/vi6tFyTF0xVPzFQu6F8n//Z',
    source: 'cat.jpg',
    size: {
      width:350,
      height:280
    }
  };
});
